# SPDX-License-Identifier: GPL-2.0
#
# Makefile for HW Random Number Generator (RNG) device drivers.
#

CFLAGS_exyswd-rng.o += -Wno-missing-prototypes

obj-$(CONFIG_HW_RANDOM_EXYNOS_SWD) += exyswd-rng.o
