# SPDX-License-Identifier: GPL-2.0
CFLAGS_smfc-dev.o += -Wno-missing-prototypes
CFLAGS_smfc-stream-parser.o += -Wno-missing-prototypes
smfc-objs := smfc-dev.o smfc-v4l2-ioctls.o smfc-regs.o smfc-stream-parser.o
obj-$(CONFIG_VIDEO_EXYNOS_SMFC) += smfc.o
