# SPDX-License-Identifier: GPL-2.0

CFLAGS_samsung-iommu.o += -Wno-missing-prototypes
CFLAGS_samsung-secure-iova.o += -Wno-missing-prototypes

obj-$(CONFIG_KVM_DUMMY_IOMMU) += kvm-dummy-iommu.o
obj-$(CONFIG_SAMSUNG_IOMMU) += samsung_iommu.o
samsung_iommu-objs += samsung-iommu.o samsung-iommu-fault.o
obj-$(CONFIG_SAMSUNG_IOMMU_GROUP) += samsung-iommu-group.o
obj-$(CONFIG_SAMSUNG_SECURE_IOVA) += samsung-secure-iova.o
obj-$(CONFIG_EXYNOS_PCIE_IOMMU) += exynos-pcie-iommu.o