# SPDX-License-Identifier: GPL-2.0-only
#
# Copyright (C) 2021, Google LLC

CFLAGS_bc_max77759.o += -Wno-missing-prototypes
CFLAGS_max77759_helper.o += -Wno-missing-prototypes
CFLAGS_slg46826.o += -Wno-missing-prototypes
CFLAGS_tcpci_fusb307.o += -Wno-missing-prototypes
CFLAGS_tcpci_max77759.o += -Wno-missing-prototypes

obj-$(CONFIG_TYPEC_FUSB307)             += tcpci_fusb307.o slg46826.o
obj-$(CONFIG_USB_PSY)                   += usb_psy.o
obj-$(CONFIG_TYPEC_MAX77759)            += tcpci_max77759.o max77759_helper.o
obj-$(CONFIG_TYPEC_MAX77759)            += bc_max77759.o
obj-$(CONFIG_TYPEC_MAX77759)            += max77759_contaminant.o
obj-$(CONFIG_TYPEC_COOLING_DEV)         += usbc_cooling_dev.o

# This gives the drivers access to the tcpci.h header
ccflags-y := -I$(srctree)/drivers/usb/typec
