# SPDX-License-Identifier: GPL-2.0
#
# Makefile for USB Host Controller Drivers
#

ccflags-y			+= -I$(srctree)/drivers/usb
CFLAGS_xhci-exynos.o += -Wno-missing-prototypes
obj-$(CONFIG_USB_XHCI_EXYNOS)	+= xhci-exynos.o
